### ISSUE TITLE
Switching between Parking allowed and Parking never allowed does not clear existing selections

### ISSUE THREAD

**Issue by theolampert** [parkplatz-transform/parkplatztransform-frontend#12]
- It's possible to create invalid subsegment state by selecting "never allowed" filling in some information and then switching to "allowed" - the data should be reset when switching between.

**Comment by henrymoews** [comment]
I think it only should be replaced when the segment is saved. Before it might be nice for the user to switch back and forth and still see the data.  But for simplification, we could clear it immediately, too.

**Comment by theolampert** [comment]
Yes, that's true. A generic serializing function for segments and subsegments might make sense to remove or warn about any invalid state.

Edit: Another thought, you'd still display an invalid state in the JSON preview and the download button would potentially also be invalid.

**Comment by henrymoews** [comment]
I see your point. I don't have a good solution, though...
Disabling the download button while some segments are not saved? Probably not...

Maybe, we should go on with more auto saving. What if we save the segment whenever the user moves the mouse away from the form view OR clicks on the save button. Next to the save button we could print the last save timestamp.

**Comment by henrymoews** [comment]
Bonus: We should run some validation checks before actually sending a segment to the server.

**Comment by theolampert** [comment]
@henrymoews The form is a bit smarter about validating now and I added the necessary changes to sanitize a segment before sending it. Would like to test everything again tomorrow but I think we can close this.
