### ISSUE TITLE
"Successfully deleted 1 segments"

### ISSUE THREAD

**Issue by henrymoews** [parkplatz-transform/parkplatztransform-frontend#25]
-> 1 segment (no plural)

**Comment by theolampert** [comment]
oder "1 abschnitt gelöscht", "{n} abschnitte gelöscht" ?

**Comment by henrymoews** [comment]
Grammatisch richtig, aber wir müssen noch die deutschen Worte diskutieren.

Singular: I'd just go with "Abschnitt gelöscht" (without a number)
Plural: "n Abschnitte gelöscht"

I'll start a discussion on slack about the terms.
